### ISSUE TITLE
script_template.py & client/actions folder

### ISSUE THREAD

**Issue by cwytko** [feltus/BDSS#135]
For the stand-alone executable, during the Pyinstallation using the client.spec, the file 'script_template.py' file is no longer available; preventing the installation unless I comment our or delete that requirement in the client.spec. The file was deleted on the commit with the following hash dd82fbfeb857c946f115d6389916dbb5fb2bd9d2. I was wondering what significance this file had. I also have an issue within File "client/__main__.py", line 26:

26: from .actions import action_module, available_action_info

Any clarification or help would be very appreciated.

Thank you

**Comment by nawatts** [comment]
Yes, script_template.py can be removed from client.spec. I pushed a commit to do so just now (da1e8d6fd3efefd9ba987bf176e0da4918c037a7). It was part of an old feature that was removed where the BDSS client would generate a standalone script to run specific transfers. And I forgot to update the PyInstaller configuration after that.

Could you elaborate on the issue in client/main.py?

**Comment by cwytko** [comment]
I'm attempting to use BDSS as an external tool in galaxy.
This is the error message I get in the history window:

Fatal error: Exit code 124 (Error) Traceback (most recent call last): File "run.py", line 22, in <module> File "/tmp/pip-build-5lb56x/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module File "client/__main__.py", line 26


Within the the bdss.xml I have the executable path (on line 7) go to the ./client/dist/bdss executable. I'm not sure if that was correct.

**Comment by nawatts** [comment]
I'm seeing a similar error when running the executable built with PyInstaller. I'll investigate and have to get back to you.

**Comment by nawatts** [comment]
f2a049e2da54e1ae6f8cbd278ed0f094c0e4b5b6 adds the [six](https://pypi.python.org/pypi/six) package as a [hidden import](https://pythonhosted.org/PyInstaller/when-things-go-wrong.html#listing-hidden-imports) in the PyInstaller configuration. This fixed my issue with the PyInstaller build. 

Could you try rebuilding the BDSS client with PyInstaller? https://github.com/feltus/BDSS/blob/master/client/docs/Installation.md#stand-alone-executable describes options for how to do that.

**Comment by cwytko** [comment]
I re-cloned the repository and ran the PyInstaller again and still received the same error. I'm running Ubuntu 16.04, and default the distro includes 2.7 and 3.5, the default python environment is 2.7. Do you think this would have something to do with this?
Thank you for your fast response on Friday and apologies for my belated response, I am but a lonely undergrad.

**Comment by nawatts** [comment]
Thanks for your patience and your feedback.

It does look like the Python version is the cause of this issue. The BDSS client requires Python 3.4+. If you have 3.5 available on the system, the easiest thing to do would be create a [virtualenv](http://docs.python-guide.org/en/latest/dev/virtualenvs/) using Python 3, activate it, install requirements with pip, then install and run PyInstaller. Something along the lines of:
```Shell
virtualenv -p /path/to/python3 venv
source venv/bin/activate
pip install -r requirements.txt
pip install pyinstaller==3.2
cd /path/to/BDSS/client
pyinstaller --clean --onefile client.spec
```

To check that the executable works:
```Shell
deactivate
./dist/bdss -h
```

There's also a `bundle` script in the scripts folder that will do all this for you, but it also downloads and compiles Python 3.5, which isn't necessary in your case but may be more convenient. Though compiling Python may require installing a few OS packages. More info on that at https://github.com/feltus/BDSS/blob/master/client/docs/Installation.md#stand-alone-executable.

**Comment by cwytko** [comment]
Thank you!
It showed the help message and I ran the tool on galaxy it does its magic now.
Thank you for your help!

**Comment by nawatts** [comment]
Excellent! Please don't hesitate to reach out with any future issues or general feedback about the tool.
